# Generated by Django 6.0.2 on 2026-02-27 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='selected_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='world.city'),
        ),
    ]
