# Generated by Django 6.0.2 on 2026-03-01 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('WALK', 'Walk'), ('CYCLE', 'Cycle'), ('TRANSIT', 'Public transport'), ('MIXED', 'Mixed / Any')], max_length=20)),
                ('group_limits', models.CharField(help_text='Format: min-max (e.g. 1-1, 1-4, 3-8)', max_length=20)),
                ('duration', models.PositiveSmallIntegerField(help_text='Duration in minutes')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
