# Generated by Django 6.0.2 on 2026-03-01 22:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0001_initial'),
        ('world', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_size', models.PositiveSmallIntegerField()),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('steps', models.PositiveIntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('proof_file', models.FileField(blank=True, null=True, upload_to='proofs/')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('ABANDONED', 'Abandoned')], default='IN_PROGRESS', max_length=20)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quest_runs', to='world.city')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='quests.questtemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_runs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
